hyperparameters:
  # not model
  batch_size: 512
  num_workers: 2
  epochs: 10

  # model
  input_shape: [3, 96, 96] # [channels, height, width]
  dropout: 0.25 # probability
  linear1: 1024
  linear2: 512
  classes: 2

  # convolution layers - [out, kernel_size, stride, padding]
  conv1: [32,  3, 1, 1]
  conv2: [64, 3, 1, 1]
  conv3: [128, 3, 1, 1]
  conv4: [256, 3, 1, 1]
  conv5: [512, 3, 1, 1]